# -*- coding: utf-8 -*-
"""akash_update.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fd_bVVLZjgbtdkiSNysC-O8dfnsQOca1
"""

!pip install praw
import praw
import time
import requests #idk why we need request? but ok
import requests.auth
import pandas as pd

reddit = praw.Reddit(
     client_id="wal33qeX5QhkVQ",
     client_secret="5Jv5XrScw3sTCuHE18j-YOUzeaKBjw",
     user_agent="script:test_app:v0.1 (by u/Comprehensive-Self39)"
 )

#^SETUP CODE

#Importing the CSV from GitHub
url = 'https://raw.githubusercontent.com/enanpurrp/Debullshitiser/main/options.csv'
options_df = pd.read_csv(url, index_col=0)
url = 'https://raw.githubusercontent.com/enanpurrp/Debullshitiser/main/financialindependence(1).csv'
finInd_df = pd.read_csv(url, index_col=0)
url = 'https://raw.githubusercontent.com/enanpurrp/Debullshitiser/main/stocks.csv'
stocks_df = pd.read_csv(url, index_col=0)
url = 'https://raw.githubusercontent.com/enanpurrp/Debullshitiser/main/wallstreetbets.csv'
WSB_df = pd.read_csv(url, index_col=0)

#adding data to csv files: data is added from the "top of last month" field, and as long as the top isn't
#lower than the UTC, it'll be added!(create's a new pandas dataframe and adds it)
def update_CSV(pdataframe, subreddit):
  latest = pdataframe['TimeStamp'].max()
  #^find the most recent post from these posts
  columns = ['Title', 'Flair', 'Score of Post', 'ID', 'URL', 'TimeStamp', 'Message body', '#Comments', 'SubReddit']
  accepted_tags_WSB = ['None', 'Charts', 'Earnings Thread', 'Gain', 'Loss', 'News'] 
  title = []; flair = []; score = []; id = []; url = []; creation = []; message = []; numComments = []; label=[];
  for submission in reddit.subreddit(subreddit).top("week"):
    if (subreddit == 'wallstreetbets'):
      if submission.link_flair_text in accepted_tags_WSB:
        if submission.over_18 == False:
          if submission.created_utc > latest:
            numComments.append(submission.num_comments)
            flair.append(submission.link_flair_text)
            title.append(submission.title)
            score.append(submission.score)
            id.append(submission.id)
            url.append(submission.url)
            creation.append(submission.created_utc)
            message.append(submission.selftext)
            label.append(subreddit)
    else:
      if submission.created_utc > latest:
        numComments.append(submission.num_comments)
        flair.append(submission.link_flair_text)
        title.append(submission.title)
        score.append(submission.score)
        id.append(submission.id)
        url.append(submission.url)
        creation.append(submission.created_utc)
        message.append(submission.selftext)
        label.append(subreddit)

  extract_array = [title, flair, score, id, url, creation, message, numComments, label]
  update_dict = dict(zip(columns, extract_array))
  update_df = pd.DataFrame(update_dict)
  return pdataframe.append(update_df, ignore_index=True)

#testruns

options_df = update_CSV(options_df, 'options')
finInd_df = update_CSV(finInd_df, 'financialindependence')
stocks_df = update_CSV(stocks_df, 'stocks')
WSB_df = update_CSV(WSB_df, 'wallstreetbets')

